Feat/error improvements
grafana/har-to-k6 pull request #93
Opened 2021-12-08 11:50 UTC by EdvinasDaugirdas

Clean up `InvalidArchiveError` error messages and extend with two properties:

- `path`: specifies the full path where the validation error has happened
- `indexes`: specifies the indexes where the validation error has happened

Example from CLI:

![Screenshot 2021-12-08 at 13 45 26](https://user-images.githubusercontent.com/10167318/145203454-cc11c697-f244-47f4-8299-a7cbf5dd6c72.png)

Example from programmatic use:

![Screenshot 2021-12-08 at 13 50 06](https://user-images.githubusercontent.com/10167318/145203772-13c2e894-1f19-456a-bc04-939aaf729c77.png)

2022-04-26 07:06 UTC, w1kman requested changes
`isPlainObject` is pretty strict. I stumbled upon the "... must be an Object" error and had a WTF-moment when I indeed passed an Object. 

`non-negative` is more readable and arguably a more correct form of `nonnegative`.

2022-04-26 07:06 UTC, w1kman commented on src/validate/sleep.js
> +        `Sleep before must be a nonnegative number`
Perhaps: "non-negative" rather than "nonnegative"

2022-04-26 07:06 UTC, w1kman commented on src/validate/sleep.js
> +        `Sleep after must be a nonnegative number`
Perhaps: "non-negative" rather than "nonnegative"

2022-04-26 07:06 UTC, w1kman commented on src/validate/sleep.js
> +      `Sleep must be a nonnegative number`
Perhaps: "non-negative" rather than "nonnegative"

2022-04-26 07:06 UTC, w1kman commented on src/validate/variable.js
> +      `Variable type must be a nonnegative integer`
Perhaps: "non-negative" rather than "nonnegative"

2022-04-26 07:06 UTC, w1kman commented on src/validate/variables.js
> +        `Variable must be an object`
"Variable must be a plain object"

2022-04-26 08:38 UTC, EdvinasDaugirdas commented
@w1kman agree with your suggestions. Updated the PR accordingly.

2022-06-14 11:57 UTC, w1kman approved these changes
LGTM!

2022-06-14 11:58 UTC, merged